# Generated by Django 4.1.7 on 2023-03-07 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(blank=True, max_length=40)),
                ('subtítulo', models.CharField(blank=True, max_length=40)),
                ('cuerpo', models.TextField(blank=True, max_length=500)),
                ('autor', models.CharField(blank=True, max_length=40)),
                ('fecha', models.DateTimeField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagen-blog')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
