# Generated by Django 4.1.7 on 2023-03-07 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppBlogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='subtítulo',
            new_name='subtitulo',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='título',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='user',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='autor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='cuerpo',
            field=models.TextField(),
        ),
    ]
