# Generated by Django 4.1.7 on 2023-03-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlogs', '0002_rename_subtítulo_blogs_subtitulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='fecha',
            field=models.DateField(blank=True),
        ),
    ]
