# Generated by Django 4.1.7 on 2023-03-08 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppBlogs', '0003_alter_blogs_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='subtitulo',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='titulo',
            field=models.CharField(max_length=40),
        ),
    ]
