# Generated by Django 4.1.7 on 2023-03-08 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlogs', '0006_alter_blogs_options_alter_blogs_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=40)),
                ('comentario', models.TextField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBlogs.blogs')),
            ],
            options={
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
