# Generated by Django 4.1.7 on 2023-03-08 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlogs', '0007_comentarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentarios',
            new_name='Mensajes',
        ),
        migrations.AlterModelOptions(
            name='mensajes',
            options={'verbose_name_plural': 'Mensajes'},
        ),
    ]
