# Generated by Django 4.1.7 on 2023-03-08 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlogs', '0008_rename_comentarios_mensajes_alter_mensajes_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajes',
            name='nombre_usuario',
        ),
    ]
