# Generated by Django 4.1.7 on 2023-03-08 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlogs', '0010_alter_mensajes_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensajes',
        ),
    ]
