# Generated by Django 4.1.7 on 2023-03-08 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlogs', '0012_comentarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentarios',
        ),
    ]
