# Generated by Django 4.1.7 on 2023-03-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditarUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('info_personal', models.CharField(max_length=500)),
                ('link', models.URLField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Info - Usuarios',
            },
        ),
    ]
