# Generated by Django 4.1.7 on 2023-03-03 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppProfile', '0002_remove_editarusuario_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editarusuario',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
