# Generated by Django 4.1.7 on 2023-03-03 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProfile', '0004_rename_info_personal_editarusuario_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditarUsuario',
        ),
    ]
