# Generated by Django 4.1.7 on 2023-03-05 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProfile', '0009_usuariopersonalizado_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContraseñaPersonalizada',
        ),
    ]
