# Generated by Django 4.1.7 on 2023-03-05 16:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppProfile', '0010_delete_contraseñapersonalizada'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsuarioPersonalizado',
            new_name='Perfil',
        ),
    ]
