# Generated by Django 4.1.7 on 2023-03-05 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProfile', '0014_rename_user_perfil_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='usuario',
            new_name='user',
        ),
    ]
