# Generated by Django 4.1.7 on 2023-03-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProfile', '0017_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfiles',
            options={'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='imagen_perfiles'),
        ),
    ]
