# Generated by Django 4.1.7 on 2023-03-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProfile', '0018_alter_perfiles_options_alter_perfiles_imagen_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='imagen_perfil'),
        ),
    ]
