# Generated by Django 4.1.7 on 2023-03-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProfile', '0019_alter_perfiles_imagen_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiles',
            name='imagen_perfil',
        ),
        migrations.AddField(
            model_name='perfiles',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
