# Generated by Django 4.1.7 on 2023-03-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProfile', '0021_alter_perfiles_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles',
            name='avatar',
            field=models.ImageField(blank=True, default='blank.png', null=True, upload_to='avatares'),
        ),
    ]
