# Generated by Django 4.1.7 on 2023-03-06 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProfile', '0022_alter_perfiles_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiles',
            name='avatar',
        ),
    ]
