# Generated by Django 4.1.7 on 2023-03-07 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProfile', '0025_perfiles_imagen_delete_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiles',
            name='imagen',
        ),
    ]
