# Generated by Django 4.1.7 on 2023-03-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProfile', '0028_perfiles_imagen_delete_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
