# Generated by Django 4.1.7 on 2023-03-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProfile', '0029_alter_perfiles_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='avatares'),
        ),
    ]
