# Generated by Django 4.1.7 on 2023-03-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProfile', '0031_alter_perfiles_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles',
            name='link',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
