# Generated by Django 4.1.7 on 2023-03-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProfile', '0032_alter_perfiles_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
