# Generated by Django 4.1.7 on 2023-03-07 19:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppProfile', '0034_alter_perfiles_imagen_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Perfiles',
            new_name='Perfil',
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
