# Generated by Django 4.1.7 on 2023-03-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProfile', '0037_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='logo',
            field=models.ImageField(blank=True, default='blank.png', null=True, upload_to='imagen-avatar'),
        ),
    ]
