# Generated by Django 4.1.7 on 2023-03-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProfile', '0038_alter_avatar_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='imagen-avatar'),
        ),
    ]
